//! The modules MixDB is made of. One folder each, and one block of the list below each.

pub mod db;

/// Every command of every module.
///
/// One list, because Tauri takes exactly one `invoke_handler` and `generate_handler!` needs its
/// paths written out rather than collected — but split into blocks by owner, and each block is
/// that module's own to edit.
///
/// Fixed to [`tauri::Wry`] rather than generic over the runtime: a command that takes an
/// `AppHandle` takes `AppHandle<Wry>`, which satisfies `CommandArg` for that one runtime and not
/// for an unknown `R`. `lib.rs` builds on `Wry` too, so nothing is given up by saying so here.
pub fn handler() -> impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        // ── shared ──
        crate::secrets::secrets_save,
        crate::secrets::secrets_load,
        crate::secrets::secrets_delete,
        // ── db ──
        db::commands::connect_db,
        db::commands::disconnect_db,
        db::commands::test_ssh_tunnel,
        db::commands::mysql_query,
        db::commands::mysql_list_databases,
        db::commands::mysql_server_info,
        db::commands::mysql_list_tables,
        db::commands::mysql_table_stats,
        db::commands::mysql_table_data,
        db::commands::mysql_update_row,
        db::commands::mysql_insert_rows,
        db::commands::mysql_delete_rows,
        db::commands::mysql_table_structure,
        db::commands::mysql_schema_outline,
        db::commands::mysql_collations,
        db::commands::mysql_dump,
        db::commands::mysql_restore,
        db::commands::mysql_drop_database,
        db::commands::mysql_create_database,
        db::commands::mysql_create_table,
        db::commands::mysql_rename_table,
        db::commands::mysql_drop_table,
        db::commands::mysql_add_column,
        db::commands::mysql_modify_column,
        db::commands::mysql_drop_column,
        db::commands::mysql_add_index,
        db::commands::mysql_modify_index,
        db::commands::mysql_drop_index,
        db::commands::mysql_run_script,
        db::commands::mysql_cancel_query,
        db::commands::mysql_validate_sql,
        db::commands::postgres_query,
        db::commands::postgres_list_databases,
        db::commands::postgres_server_info,
        db::commands::postgres_list_tables,
        db::commands::postgres_table_stats,
        db::commands::postgres_table_data,
        db::commands::postgres_update_row,
        db::commands::postgres_insert_rows,
        db::commands::postgres_delete_rows,
        db::commands::postgres_table_structure,
        db::commands::postgres_collations,
        db::commands::postgres_schema_outline,
        db::commands::postgres_run_script,
        db::commands::postgres_validate_sql,
        db::commands::postgres_cancel_query,
        db::commands::postgres_create_database,
        db::commands::postgres_drop_database,
        db::commands::postgres_create_table,
        db::commands::postgres_rename_table,
        db::commands::postgres_drop_table,
        db::commands::postgres_add_column,
        db::commands::postgres_modify_column,
        db::commands::postgres_drop_column,
        db::commands::postgres_add_index,
        db::commands::postgres_modify_index,
        db::commands::postgres_drop_index,
        db::commands::postgres_dump,
        db::commands::postgres_restore,
        db::commands::mongo_list_databases,
        db::commands::mongo_server_info,
        db::commands::mongo_list_collections,
        db::commands::mongo_collection_stats,
        db::commands::mongo_dump,
        db::commands::mongo_restore,
        db::commands::mongo_drop_database,
        db::commands::mongo_create_collection,
        db::commands::mongo_rename_collection,
        db::commands::mongo_drop_collection,
        db::commands::mongo_find,
        db::commands::mongo_collection_page,
        db::commands::mongo_next_ids,
        db::commands::mongo_insert_documents,
        db::commands::mongo_update_document,
        db::commands::mongo_delete_document,
        db::commands::redis_command,
        db::commands::redis_server_info,
        db::commands::redis_list_databases,
        db::commands::redis_select_db,
        db::commands::redis_scan_keys,
        db::commands::redis_key_value,
        db::commands::redis_delete_keys,
        db::commands::tools_status,
        db::commands::tools_ready,
        db::commands::tools_downloadable,
        db::commands::tools_install,
        db::commands::tools_uninstall,
        db::commands::tools_set_path,
    ]
}
